# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rounds', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('w', 'waiting'), ('p', 'in progress'), ('f', 'finished')], default='w', max_length=1)),
                ('timeout', models.PositiveIntegerField(default=86400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gcm_registration_id', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.Image')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inviting_player', models.BooleanField(default=False)),
                ('date_invited', models.DateTimeField(auto_now_add=True)),
                ('invitation_status', models.CharField(choices=[('i', 'invited'), ('a', 'accepted'), ('d', 'declined')], default='i', max_length=1)),
                ('date_responded', models.DateTimeField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRoundDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_storyteller', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='matches.Image')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='matches.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_current_round', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('w', 'waiting'), ('s', 'submit storyteller'), ('o', 'submit others'), ('v', 'submit votes'), ('f', 'finished')], default='w', max_length=1)),
                ('story', models.CharField(blank=True, max_length=256)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Match')),
                ('players', models.ManyToManyField(through='matches.PlayerRoundDetails', to='matches.Player')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='playerrounddetails',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Round'),
        ),
        migrations.AddField(
            model_name='playerrounddetails',
            name='vote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='matches.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='matches.PlayerMatchDetails', to='matches.Player'),
        ),
    ]
