# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20160822_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerrounddetails',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_story', to='matches.Image'),
        ),
        migrations.AlterField(
            model_name='playerrounddetails',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voted_by', to='matches.Player'),
        ),
    ]
