# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20160826_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('last_modified',), 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='match',
            name='total_rounds',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
