# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20160822_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player_details',
        ),
        migrations.RemoveField(
            model_name='round',
            name='player_details',
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='matches', through='matches.PlayerMatchDetails', to='matches.Player'),
        ),
        migrations.AddField(
            model_name='round',
            name='players',
            field=models.ManyToManyField(related_name='rounds', through='matches.PlayerRoundDetails', to='matches.Player'),
        ),
        migrations.AlterField(
            model_name='playermatchdetails',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_details', to='matches.Match'),
        ),
        migrations.AlterField(
            model_name='playermatchdetails',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_match_details', to='matches.Player'),
        ),
        migrations.AlterField(
            model_name='playerrounddetails',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_round_details', to='matches.Image'),
        ),
        migrations.AlterField(
            model_name='playerrounddetails',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_round_details', to='matches.Player'),
        ),
        migrations.AlterField(
            model_name='playerrounddetails',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_round_details', to='matches.Round'),
        ),
    ]
