# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20160822_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image_url',
        ),
    ]
