application: diris-app
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: diris.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: diris.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: diris.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: diris.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.*
    - bin/.*
    - include/.*
    - lib/.*
    - man/.*
    - sitepackages/dev*
    - \.storage.*
    - \.git.*
    - (.*)\.pyc
    - dixit/.*
